### PR TITLE
Fix ps:set-restart-policy being deprecated on dokku 0.22.0

### PR DESCRIPTION
**Pull request by whollacsek**
Fixing this issue: https://github.com/badsyntax/dokku-discourse/issues/10

### CODE REVIEW

**Comment by badsyntax** [comment]
Thanks for this. Can you update the dokku version in the workflow test.yml file to get the tests to pass?

**Comment by whollacsek** [comment]
Done it should be good in few moments 👍

**Comment by badsyntax** [comment]
Test still failing due to removal of `ps_stop` (see https://github.com/dokku/dokku/pull/4149)

I believe you can replace this line:

https://github.com/badsyntax/dokku-discourse/blob/1852fdd5585ebac672eaa16dc4dd68bb712d369a/internal-functions#L105

With

```sh
[[ -n $("$DOCKER_BIN" ps -q -f ancestor="dokku/$APP_NAME") ]] && dokku ps:stop "$APP_NAME"
```

Once that change is made i'll merge, and then i'll follow up with some additional changes for better support across different versions.

**Comment by badsyntax** [comment]
Thanks for the contribution. I have added a follow up PR with https://github.com/badsyntax/dokku-discourse/pull/12

**Pull request merged**
